---
title: "Задание по лекции 01"
author: "Игорь Мирошниченко"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---
# Задание 1

Написать код, который вычисляет сумму всех чисел, удовлетворяющих следующие условия:

* положительные целые числа от 1 до 1_000_000_002 (один миллиард два) включительно
* которые нацело (без остатка) делятся на 3 (пример: 3, 6, 9, ...)
* и которые не заканчиваются на 4 и 7 (пример заканчивающихся на 4 и 7: 24, 27, 54, 57 ...)

Результат суммы ввести в поле ниже.
В поле нужно ввести только число, являющееся ответом, без пробелов и других символов.

```{python}
def sum_div(a, b, m):
    s = 0
    for i in range (a, b+1):
      if (i % m) == 0 and (i % 10) != 4 and (i % 10) != 7:
          s += i
    return(s)
```

```{python}
# sum_div(1, 1_000_000_002, 3)
```


# Задание 2
На вход поступает текстовый файл из 3-х тысяч строк
**Формат файла:**
    "арифметическая операция"    "целое число #1"    "целое число #2"
Разделитель - 4 пробела


Нужно подготовить текстовый файл из 1 строки.
Строка содержит набор из 3-х тысяч чисел, разделенных запятой. 
После последнего числа запятая не ставится.
каждое число - результат операции: 
    "результирующее целое число" = "целое число #1" применить "арифметическая операция" "целое число #2"

**Пример входного файла:**
```{}
+    5    4
-    -10449    -7623
**    2    10
```

**Пример выходного файла (для примера входного файла выше):**
```{}
9,-2826,1024
```

**Допустимые операции:**
* + (сложение)
* - (вычитание)
* * (умножение)
* // (целочисленное деление) (для этой операции подаются только положительные числа)
* % (остаток от деления) (для этой операции подаются только положительные числа)
* ** (возведение в степень) (для этой операции подаются только положительные числа)

```{python}
input = open("test_input_file_1.txt", "r")
all_data = input.readlines()
type(all_data)
print(all_data)

all_data[0][0]

import pandas as pd

input = pd.read_csv('test_input_file_1.txt', sep="    ", header=None)
input.columns = ["a", "b", "c"]
input["result"] = input["b"].astype(str) + input["a"].astype(str) + input["c"].astype(str)
x = pd.eval(input["result"])
type(x)

df = pd.DataFrame(x)
```

