---
title: "Введение в Python"
author: "Игорь Мирошниченко"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE)
```

# 0.
* [Материалы лекции](github.com/ermakovpetr/open-ml-course/blob/main/003%20Введение%20в%20python/python%20base.ipynb)
* [Видео лекции](https://www.youtube.com/watch?v=rWxD7vZdldY)

# 1. int and float - числа и переменные

```{python}
int_var_1 = 1000000
int_var_2 = 1_000_000

int_var_1

int_var_2

type(int_var_1)

type(int_var_2)

float_var_1 = 123.456
float_var_2 = 1.0
float_var_3 = .123456

type(float_var_1)
type(float_var_2)
type(float_var_3)
```

# 2. Калькулятор

```{python}
123 + 456

654 - 321

5 * 9

999 / 9 # float!

12 % 10 # остаток от деления

12 // 10 # целочисленное деление

2 ** 10 # степень
```

# 3. Синтаксический сахар

```{python}
a = 10
b = 20
c = a + b
c
```

```{python}
a = 10
b = 20
a = a + b
a
```

```{python}
a = 10
b = 20
a += b # синтаксический сахар
a
a /= b 
a
```

# 4. Строки
Разные форматы записи строк
```{python}
str_var_1 = 'Hello'
str_var_1

str_var_2 = "Hello"
str_var_2

str_var_3 = '''Hello'''
str_var_3

str_var_4 = """Hello"""
str_var_4

str_var_5 = 'Hel\'lo' # экранирование символа
str_var_5

str_var_6 = "Hel'lo" # комбинирование
```

Проверим тип переменной
```{python}
type(str_var_1)
```

Длинный вариант записи строки
```{python}
long_str_var_1 = '''You
shall
not
pass!'''

print(long_str_var_1) # если в RStudio - надо запускать через print()
```

Еще варианты длинных запиcей:
```{python}
long_str_var_2 = """Ash nazg durbatulûk,\n\tash nazg gimbatul,\nAsh nazg thrakatulûk\n\tagh burzum-ishi krimpatul."""

print(long_str_var_2)
```

Склейка строк (конкатенация):
```{python}
"One" + 'Ring'

print("Lord" + " " + "of" + " " + "the" + " " + "Rings")
```

Умножение строк :
```{python}
"Hobbit " * 4
```

Узнать длину строки:
```{python}
len(long_str_var_2)
```


Типизация:
```{python}
int("2") + 3

"2" + str(3)
```

# 5. Списки.
По сути как вектор, но может иметь разные типы элементы
```{python}
[1, 5, 10]

my_list = ['Zero', 1, "2", [], [111, "text"]]
my_list
type(my_list)
```

Индексация списков (начинается с 0):
```{python}
my_list[0]

my_list[4]
```

Смена элементов списка (но нельзя добавлять):
```{python}
my_list[3] = "World!"

my_list
```

Срез по списку:
```{python}
# со второго и до конца
my_list[1:]

# правая граница не включается!
my_list[:3]

# с первого (если считать с 0) до второго (правая граница не включается)
my_list[1:3]

# срез с шагом
my_list_int = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_list_int[3:9:2] # 2 - указывает шаг.
my_list_int[::3] # от начала до конца с шагом 3
my_list_int[::-1] # с конца в начало - перевернуть список

my_list_int[2:-2:2]
# 0  1  2     .     .     -2 -1
# 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

my_list_int[-7:-2]
```


Операции над списками
```{python}
# Склейка
[1, 2, 3] + ["one", "two", "three"]

# Повторение
[1, 2, 3] * 3

# Сортировка по возрастанию
numbers_list = [4, 8, -5, -3, 1]
sorted(numbers_list)

# По спаданию
sorted(numbers_list, reverse = True)

# Можно и с текстом
gendalf_list = ["You", "shall", "not", "pass!"]
sorted(gendalf_list)

# Со строками работает необычно (дробит на отдельные буквы)
print(long_str_var_1)
sorted(long_str_var_1)
```

# 6. Булевые значения
Есть две константы: True (да/истина), False (нет/лож)

Сравнение
```{python}
3 > 5

2 <= 10

25 == 5**2

9 != 2
```

Использование операторов `and` и `or` для булевых значений
Таблица для `and`:

| var1      |   var2    |   Результат    |
|---    |---    |---    |
|   True    |   True    |    True   |
|    True   |   False    |   False    |
|    False   |   True    |    False   |
|     False  |   False    |   False    |

Таблица для `or`:

| var1      |   var2    |   Результат    |
|---    |---    |---    |
|   True    |   True    |    True   |
|    True   |   False    |   True    |
|    False   |   True    |    True   |
|     False  |   False    |   False    |

`not` меняет на противоположное: был `True` стал `False` и наоборот.

```{python}
temp_var = 36.6

temp_var >= 36 and temp_var <= 37

36 <= temp_var <= 37
```

# 7. Множества (set)
В множестве хранятся только уникальные значения. Но порядок значений работает необычно.
```{python}
my_set = set([10, 100, 1000, 10])
my_set
```









